package belajar_java_hibernate.entity;
// Generated Apr 8, 2017 8:28:12 PM by Hibernate Tools 4.3.1



/**
 * Dvd generated by hbm2java
 */
public class Dvd  implements java.io.Serializable {


     private String kdDvd;
     private String namaDvd;
     private String jenisDvd;
     private Long harga;

    public Dvd() {
    }

	
    public Dvd(String kdDvd) {
        this.kdDvd = kdDvd;
    }
    public Dvd(String kdDvd, String namaDvd, String jenisDvd, Long harga) {
       this.kdDvd = kdDvd;
       this.namaDvd = namaDvd;
       this.jenisDvd = jenisDvd;
       this.harga = harga;
    }
   
    public String getKdDvd() {
        return this.kdDvd;
    }
    
    public void setKdDvd(String kdDvd) {
        this.kdDvd = kdDvd;
    }
    public String getNamaDvd() {
        return this.namaDvd;
    }
    
    public void setNamaDvd(String namaDvd) {
        this.namaDvd = namaDvd;
    }
    public String getJenisDvd() {
        return this.jenisDvd;
    }
    
    public void setJenisDvd(String jenisDvd) {
        this.jenisDvd = jenisDvd;
    }
    public Long getHarga() {
        return this.harga;
    }
    
    public void setHarga(Long harga) {
        this.harga = harga;
    }




}


